spring.application.name=puntoventa
server.port=8084
# ? URL de la base de datos (ajusta el puerto y nombre si es distinto)
spring.datasource.url=jdbc:mysql://localhost:3306/punto_de_venta?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# ? Usuario y contraseña de tu base
spring.datasource.username=root
spring.datasource.password=12345

# ? Driver JDBC de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? Hibernate NO debe crear ni eliminar las tablas
spring.jpa.hibernate.ddl-auto=none

# ? Dialecto de MySQL (versión 8 o la que uses)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ? (Opcional) Mostrar SQLs en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

